In [22]:
import numpy as np
import pandas as pd

In [2]:
print("="*60)
print("NUMPY ASSIGNMENT: BANKING INDUSTRY DATA ANALYSIS")
print("=" * 60)

NUMPY ASSIGNMENT: BANKING INDUSTRY DATA ANALYSIS


In [23]:
# Create banking industry data: 10 rows × 5 columns
# Columns: customer_ID, Account_Balance, Credit_score, Transaction_count, years_Active
banking_data = np.array([
    [1001, 5000,  720, 15, 5],
    [1002, 12000, 680, 25, 8],
    [1003, 3000,  650, 10, 2],
    [1004, 15000, 800, 40, 10],
    [1005, 7000,  710, 20, 6],
    [1006, 4500,  640, 12, 3],
    [1007, 9000,  730, 30, 7],
    [1008, 2000,  600, 8,  1],
    [1009, 11000, 750, 35, 9],
    [1010, 6000,  690, 18, 4]
])


Question 1: Array Creation and Manipulation

In [4]:
print("\nQ1.1: Create a 4x4 identity matrix")
np.eye(4)


Q1.1: Create a 4x4 identity matrix


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [5]:
print("/nQ1.2: Create an array of 8 zeros")
np.zeros(8)

/nQ1.2: Create an array of 8 zeros


array([0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
print("\nQ1.3: Create an array of 6 ones")
np.ones(6)


Q1.3: Create an array of 6 ones


array([1., 1., 1., 1., 1., 1.])

In [11]:
print("\nQ1.4: Create an array with values from 0 to 15")
np.arange(15)


Q1.4: Create an array with values from 0 to 15


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [17]:
print("\nQ1.5: Create an array with 8 evenly spaced values from 0 to 100")
np.linspace(0,100,8)


Q1.5: Create an array with 8 evenly spaced values from 0 to 100


array([  0.        ,  14.28571429,  28.57142857,  42.85714286,
        57.14285714,  71.42857143,  85.71428571, 100.        ])

Question 2: Array Attributes and Information

In [ ]:
print("\nQ2.1: What is the shape of the banking_data array?")
banking_data.shape


Q2.1: What is the shape of the banking_data array


(10, 5)

In [20]:
print("\nQ2.2: What is the data type of the banking_data array?")
banking_data.dtype


Q2.2: What is the data type of the banking_data array?


dtype('int32')

In [21]:
print("\nQ2.3: What is the size (total number of elements) of the banking_data array?")
banking_data.sum()


Q2.3: What is the size (total number of elements) of the banking_data array?


91793

In [22]:
print("\nQ2.4: What is the number of dimensions of the banking_data array?")
banking_data.ndim


Q2.4: What is the number of dimensions of the banking_data array?


2

In [24]:
print("\nQ2.5: What is the memory size of the banking_data array in bytes?")
banking_data.nbytes


Q2.5: What is the memory size of the banking_data array in bytes?


200

Question 3: Indexing and Slicing

In [29]:
print("\nQ3.1: Extract the first row of banking_data")
banking_data[0]


Q3.1: Extract the first row of banking_data


array([1001, 5000,  720,   15,    5])

In [30]:
print("\nQ3.2: Extract the last row of banking_data")
banking_data[-1]


Q3.2: Extract the last row of banking_data


array([1010, 6000,  690,   18,    4])

In [31]:
print("\nQ3.3: Extract the Account_Balance column (column index 1)")
banking_data[:,1]


Q3.3: Extract the Account_Balance column (column index 1)


array([ 5000, 12000,  3000, 15000,  7000,  4500,  9000,  2000, 11000,
        6000])

In [34]:
print("\nQ3.4: Extract the first 4 rows and first 3 columns")
banking_data[:4,:3]


Q3.4: Extract the first 4 rows and first 3 columns


array([[ 1001,  5000,   720],
       [ 1002, 12000,   680],
       [ 1003,  3000,   650],
       [ 1004, 15000,   800]])

In [35]:
print("\nQ3.5: Extract rows 3 to 7 (inclusive)")
banking_data[3:8]


Q3.5: Extract rows 3 to 7 (inclusive)


array([[ 1004, 15000,   800,    40,    10],
       [ 1005,  7000,   710,    20,     6],
       [ 1006,  4500,   640,    12,     3],
       [ 1007,  9000,   730,    30,     7],
       [ 1008,  2000,   600,     8,     1]])

Question 4: Mathematical Operations

In [38]:
print("\nQ4.1: Calculate the sum of all account balances")
np.sum(banking_data[:,1])


Q4.1: Calculate the sum of all account balances


74500

In [39]:
print("\nQ4.2: Calculate the mean account balance")
np.mean(banking_data[:,1])


Q4.2: Calculate the mean account balance


7450.0

In [41]:
print("\nQ4.3: Calculate the standard deviation of account balances")
std_deviation=np.std(banking_data[:,1])
print(f"standard deviation:{std_deviation:.2f}")


Q4.3: Calculate the standard deviation of account balances
standard deviation:3990.30


In [42]:
print("\nQ4.4: Calculate the variance of account balances")
np.var(banking_data[:,1])


Q4.4: Calculate the variance of account balances


15922500.0

In [43]:
print("\nQ4.5: Calculate the median account balance")
np.median(banking_data[:,1])


Q4.5: Calculate the median account balance


6500.0

Question 5: Statistical Functions

In [44]:
print("\nQ5.1: Find the minimum and maximum account balances")
maximum_value=np.max(banking_data[:,1])
minimum_value=np.min(banking_data[:,1])
print(f"maximum value :{maximum_value}")
print(f"minimum value :{minimum_value}")


Q5.1: Find the minimum and maximum account balances
maximum value :15000
minimum value :2000


In [45]:
print("\nQ5.2: Find the minimum and maximum credit scores")
maximum_score=np.max(banking_data[:,2])
minimum_score=np.min(banking_data[:,2])
print(f"maximum credit score :{maximum_score}")
print(f"minimum credit score :{minimum_score}")



Q5.2: Find the minimum and maximum credit scores
maximum credit score :800
minimum credit score :600


In [47]:
print("\nQ5.3: Calculate the percentile values for account balances (25th, 50th, 75th)")
np.percentile(banking_data[:,1],[25,50,75])


Q5.3: Calculate the percentile values for account balances (25th, 50th, 75th)


array([ 4625.,  6500., 10500.])

In [48]:
print("\nQ5.4: Calculate the correlation between account balance and credit score")
np.corrcoef(banking_data[:,1],banking_data[:,2])


Q5.4: Calculate the correlation between account balance and credit score


array([[1.        , 0.81505618],
       [0.81505618, 1.        ]])

In [49]:
print("\nQ5.5: Calculate the covariance between account balance and credit score")
np.cov(banking_data[:,1],banking_data[:,2])


Q5.5: Calculate the covariance between account balance and credit score


array([[1.76916667e+07, 1.99277778e+05],
       [1.99277778e+05, 3.37888889e+03]])

Question 6: Array Reshaping and Manipulation

In [50]:
print("\nQ6.1: Reshape the banking_data to 5 rows × 10 columns")
banking_data.reshape(5,10)


Q6.1: Reshape the banking_data to 5 rows × 10 columns


array([[ 1001,  5000,   720,    15,     5,  1002, 12000,   680,    25,
            8],
       [ 1003,  3000,   650,    10,     2,  1004, 15000,   800,    40,
           10],
       [ 1005,  7000,   710,    20,     6,  1006,  4500,   640,    12,
            3],
       [ 1007,  9000,   730,    30,     7,  1008,  2000,   600,     8,
            1],
       [ 1009, 11000,   750,    35,     9,  1010,  6000,   690,    18,
            4]])

In [51]:
print("\nQ6.2: Flatten the banking_data to a 1D array")
banking_data.flatten()


Q6.2: Flatten the banking_data to a 1D array


array([ 1001,  5000,   720,    15,     5,  1002, 12000,   680,    25,
           8,  1003,  3000,   650,    10,     2,  1004, 15000,   800,
          40,    10,  1005,  7000,   710,    20,     6,  1006,  4500,
         640,    12,     3,  1007,  9000,   730,    30,     7,  1008,
        2000,   600,     8,     1,  1009, 11000,   750,    35,     9,
        1010,  6000,   690,    18,     4])

In [53]:
print("\nQ6.3: Transpose the banking_data")
banking_data.T


Q6.3: Transpose the banking_data


array([[ 1001,  1002,  1003,  1004,  1005,  1006,  1007,  1008,  1009,
         1010],
       [ 5000, 12000,  3000, 15000,  7000,  4500,  9000,  2000, 11000,
         6000],
       [  720,   680,   650,   800,   710,   640,   730,   600,   750,
          690],
       [   15,    25,    10,    40,    20,    12,    30,     8,    35,
           18],
       [    5,     8,     2,    10,     6,     3,     7,     1,     9,
            4]])

In [56]:
print("\nQ6.4: Split the banking_data into 2 equal parts vertically")
np.vsplit(banking_data,2)


Q6.4: Split the banking_data into 2 equal parts vertically


[array([[ 1001,  5000,   720,    15,     5],
        [ 1002, 12000,   680,    25,     8],
        [ 1003,  3000,   650,    10,     2],
        [ 1004, 15000,   800,    40,    10],
        [ 1005,  7000,   710,    20,     6]]),
 array([[ 1006,  4500,   640,    12,     3],
        [ 1007,  9000,   730,    30,     7],
        [ 1008,  2000,   600,     8,     1],
        [ 1009, 11000,   750,    35,     9],
        [ 1010,  6000,   690,    18,     4]])]

In [4]:
print("\nQ6.5: Split the banking_data into 2 equal parts horizontally")
split_horizontal = np.hsplit(banking_data, [2])

print("First Part:")
print(split_horizontal[0])

print("Second Part:")
print(split_horizontal[1])


Q6.5: Split the banking_data into 2 equal parts horizontally
First Part:
[[ 1001  5000]
 [ 1002 12000]
 [ 1003  3000]
 [ 1004 15000]
 [ 1005  7000]
 [ 1006  4500]
 [ 1007  9000]
 [ 1008  2000]
 [ 1009 11000]
 [ 1010  6000]]
Second Part:
[[720  15   5]
 [680  25   8]
 [650  10   2]
 [800  40  10]
 [710  20   6]
 [640  12   3]
 [730  30   7]
 [600   8   1]
 [750  35   9]
 [690  18   4]]


Question 7: Logical Operations and Filtering

In [9]:
print("\nQ7.1: Find customers with account balance greater than $100,000")
banking_data[banking_data[:,1]>1000000]


Q7.1: Find customers with account balance greater than $100,000


array([], shape=(0, 5), dtype=int32)

In [13]:
print("\nQ7.2: Find customers with credit score greater than 800")
banking_data[banking_data[:,2]>800]
banking_data[banking_data[:,2]>=800]


Q7.2: Find customers with credit score greater than 800


array([[ 1004, 15000,   800,    40,    10]])

In [16]:
print("\nQ7.3: Find customers with transaction count greater than 50 AND credit score less than 750")
#banking_data[(banking_data[:,3]>50)&(banking_data[:,2]<750)]
banking_data[(banking_data[:,3]>15)&(banking_data[:,2]<750)]


Q7.3: Find customers with transaction count greater than 50 AND credit score less than 750


array([[ 1002, 12000,   680,    25,     8],
       [ 1005,  7000,   710,    20,     6],
       [ 1007,  9000,   730,    30,     7],
       [ 1010,  6000,   690,    18,     4]])

In [20]:
print("\nQ7.4: Count how many customers have account balance between $10,000 and $100,000")
count=np.sum((banking_data[:,1]>=10000)&(banking_data[:,1]<=100000))
print(f"count of customers having account balance between $10,000 and $100,000 is : {count}")


Q7.4: Count how many customers have account balance between $10,000 and $100,000
count of customers having account balance between $10,000 and $100,000 is : 3


In [24]:
print("\nQ7.5: Find the index of the customer with the highest credit score")
cust_highscore=np.argmax(banking_data[:2])
print(f"customer with the highest credit score : {cust_highscore}")


Q7.5: Find the index of the customer with the highest credit score
customer with the highest credit score : 6


Question 8: Sorting and Searching

In [28]:
print("\nQ8.1: Sort the banking_data by account balance (ascending)")
banking_data[banking_data[:,1].argsort()]


Q8.1: Sort the banking_data by account balance (ascending)


array([[ 1008,  2000,   600,     8,     1],
       [ 1003,  3000,   650,    10,     2],
       [ 1006,  4500,   640,    12,     3],
       [ 1001,  5000,   720,    15,     5],
       [ 1010,  6000,   690,    18,     4],
       [ 1005,  7000,   710,    20,     6],
       [ 1007,  9000,   730,    30,     7],
       [ 1009, 11000,   750,    35,     9],
       [ 1002, 12000,   680,    25,     8],
       [ 1004, 15000,   800,    40,    10]])

In [29]:
print("\nQ8.2: Sort the banking_data by credit score (descending)")
banking_data[(-banking_data[:,2]).argsort()]


Q8.2: Sort the banking_data by credit score (descending)


array([[ 1004, 15000,   800,    40,    10],
       [ 1009, 11000,   750,    35,     9],
       [ 1007,  9000,   730,    30,     7],
       [ 1001,  5000,   720,    15,     5],
       [ 1005,  7000,   710,    20,     6],
       [ 1010,  6000,   690,    18,     4],
       [ 1002, 12000,   680,    25,     8],
       [ 1003,  3000,   650,    10,     2],
       [ 1006,  4500,   640,    12,     3],
       [ 1008,  2000,   600,     8,     1]])

In [31]:
print("\nQ8.3: Find the indices that would sort the array by years active")
banking_data[np.argsort(banking_data[:,4])]


Q8.3: Find the indices that would sort the array by years active


array([[ 1008,  2000,   600,     8,     1],
       [ 1003,  3000,   650,    10,     2],
       [ 1006,  4500,   640,    12,     3],
       [ 1010,  6000,   690,    18,     4],
       [ 1001,  5000,   720,    15,     5],
       [ 1005,  7000,   710,    20,     6],
       [ 1007,  9000,   730,    30,     7],
       [ 1002, 12000,   680,    25,     8],
       [ 1009, 11000,   750,    35,     9],
       [ 1004, 15000,   800,    40,    10]])

In [38]:
print("\nQ8.4: Find the customer with the second highest account balance")
sorted_data=banking_data[np.argsort(banking_data[:,1])]
second_highest=sorted_data[-2]
second_highest


Q8.4: Find the customer with the second highest account balance


array([ 1002, 12000,   680,    25,     8])

In [41]:
print("\nQ8.5: Find the customer with the lowest transaction count")
banking_data[np.argmin(banking_data[:,3])]


Q8.5: Find the customer with the lowest transaction count


array([1008, 2000,  600,    8,    1])

Question 9: Mathematical Functions

In [42]:
print("\nQ9.1: Calculate the absolute values of all elements")
np.abs(banking_data)


Q9.1: Calculate the absolute values of all elements


array([[ 1001,  5000,   720,    15,     5],
       [ 1002, 12000,   680,    25,     8],
       [ 1003,  3000,   650,    10,     2],
       [ 1004, 15000,   800,    40,    10],
       [ 1005,  7000,   710,    20,     6],
       [ 1006,  4500,   640,    12,     3],
       [ 1007,  9000,   730,    30,     7],
       [ 1008,  2000,   600,     8,     1],
       [ 1009, 11000,   750,    35,     9],
       [ 1010,  6000,   690,    18,     4]])

In [43]:
print("\nQ9.2: Calculate the square root of all account balances")
np.sqrt(banking_data[:,1])


Q9.2: Calculate the square root of all account balances


array([ 70.71067812, 109.5445115 ,  54.77225575, 122.47448714,
        83.66600265,  67.08203932,  94.86832981,  44.72135955,
       104.88088482,  77.45966692])

In [44]:
print("\nQ9.3: Calculate the square of all credit scores")
np.sqrt(banking_data[:,2])


Q9.3: Calculate the square of all credit scores


array([26.83281573, 26.07680962, 25.49509757, 28.28427125, 26.64582519,
       25.29822128, 27.01851217, 24.49489743, 27.38612788, 26.26785107])

In [45]:
print("\nQ9.4: Calculate the exponential of all transaction counts")
np.exp(banking_data[:,3])


Q9.4: Calculate the exponential of all transaction counts


array([3.26901737e+06, 7.20048993e+10, 2.20264658e+04, 2.35385267e+17,
       4.85165195e+08, 1.62754791e+05, 1.06864746e+13, 2.98095799e+03,
       1.58601345e+15, 6.56599691e+07])

In [46]:
print("\nQ9.5: Calculate the natural logarithm of all account balances")
np.log(banking_data[:,1])


Q9.5: Calculate the natural logarithm of all account balances


array([8.51719319, 9.39266193, 8.00636757, 9.61580548, 8.85366543,
       8.41183268, 9.10497986, 7.60090246, 9.30565055, 8.69951475])

Question 10: Advanced Operations

In [47]:
print("\nQ10.1: Calculate the cumulative sum of account balances")
np.cumsum(banking_data[:,1])


Q10.1: Calculate the cumulative sum of account balances


array([ 5000, 17000, 20000, 35000, 42000, 46500, 55500, 57500, 68500,
       74500])

In [48]:
print("\nQ10.2: Calculate the cumulative product of transaction counts")
np.cumprod(banking_data[:,3])


Q10.2: Calculate the cumulative product of transaction counts


array([        15,        375,       3750,     150000,    3000000,
         36000000, 1080000000,   50065408, 1752289280, 1476435968])

In [49]:
print("\nQ10.3: Calculate the difference between consecutive account balances")
np.diff(banking_data[:,1])


Q10.3: Calculate the difference between consecutive account balances


array([ 7000, -9000, 12000, -8000, -2500,  4500, -7000,  9000, -5000])

In [50]:
print("\nQ10.4: Calculate the gradient of account balances")
np.gradient(banking_data[:,1])


Q10.4: Calculate the gradient of account balances


array([ 7000., -1000.,  1500.,  2000., -5250.,  1000., -1250.,  1000.,
        2000., -5000.])

In [53]:
print("\nQ10.5: Calculate the histogram of account balances with 5 bins")
np.histogram(banking_data[:,1],bins=5)


Q10.5: Calculate the histogram of account balances with 5 bins


(array([3, 3, 1, 2, 1], dtype=int64),
 array([ 2000.,  4600.,  7200.,  9800., 12400., 15000.]))

Question 11: Random Numbers and Simulation

In [55]:
print("\nQ11.1: Generate 6 random integers between 1 and 1000")
np.random.randint(0,10000,6)


Q11.1: Generate 6 random integers between 1 and 1000


array([4325, 1449, 4546, 2119, 6299, 6834])

In [56]:
print("\nQ11.2: Generate 6 random floats between 0 and 1")
np.random.random(6)


Q11.2: Generate 6 random floats between 0 and 1


array([0.34335626, 0.68378185, 0.67697156, 0.42103257, 0.78753808,
       0.48373387])

In [58]:
print("\nQ11.3: Generate 6 random numbers from normal distribution (mean=700, std=100)")
np.random.normal(700,100,6)


Q11.3: Generate 6 random numbers from normal distribution (mean=700, std=100)


array([1007.2506202 ,  547.32092921,  663.58125511,  842.61758039,
        795.31947665,  656.6749455 ])

In [69]:
print("\nQ11.4: Shuffle the banking_data rows randomly")
copy_data=banking_data.copy()
banking_data1=np.random.shuffle(copy_data)
copy_data


Q11.4: Shuffle the banking_data rows randomly


array([[ 1009, 11000,   750,    35,     9],
       [ 1005,  7000,   710,    20,     6],
       [ 1003,  3000,   650,    10,     2],
       [ 1001,  5000,   720,    15,     5],
       [ 1004, 15000,   800,    40,    10],
       [ 1006,  4500,   640,    12,     3],
       [ 1007,  9000,   730,    30,     7],
       [ 1008,  2000,   600,     8,     1],
       [ 1010,  6000,   690,    18,     4],
       [ 1002, 12000,   680,    25,     8]])

In [71]:
print("\nQ11.5: Set random seed to 123 and generate 4 random numbers")
np.random.seed(123)
random_num=np.random.random(4)
random_num


Q11.5: Set random seed to 123 and generate 4 random numbers


array([0.69646919, 0.28613933, 0.22685145, 0.55131477])

Question 12: Linear Algebra Operations

In [72]:
print("\nQ12.1: Calculate the dot product of account balance and credit score columns")
np.dot(banking_data[:,1],banking_data[:,2])


Q12.1: Calculate the dot product of account balance and credit score columns


53720000

In [74]:
print("\nQ12.2: Calculate the cross product of first two rows")
np.cross(banking_data[0,:3],banking_data[1,:3])


Q12.2: Calculate the cross product of first two rows


array([ 5100000,   150600, -9070000])

In [77]:
print("\nQ12.3: Calculate the norm (magnitude) of the account balance column")
np.linalg.norm(banking_data[:,1])


Q12.3: Calculate the norm (magnitude) of the account balance column


26725.456029785535

In [82]:
print("\nQ12.4: Create a 3x3 matrix and calculate its determinant")
matrix_3x3=np.random.randint(0,10,(3,3))
matrix_determinant=np.linalg.det(matrix_3x3)
print(f"Matrix:\n{matrix_3x3}")
print(f"Determinant: {matrix_determinant}")


Q12.4: Create a 3x3 matrix and calculate its determinant
Matrix:
[[3 5 0]
 [2 6 2]
 [4 4 6]]
Determinant: 63.99999999999998


In [83]:
print("\nQ12.5: Calculate the inverse of the 3x3 matrix")
np.linalg.inv(matrix_3x3)


Q12.5: Calculate the inverse of the 3x3 matrix


array([[ 0.4375 , -0.46875,  0.15625],
       [-0.0625 ,  0.28125, -0.09375],
       [-0.25   ,  0.125  ,  0.125  ]])

Question 13: String Operations

In [85]:
print("\nQ13.1: Convert all customer IDs to strings")
banking_data[:,1].astype(str)


Q13.1: Convert all customer IDs to strings


array(['11000', '2000', '6000', '7000', '15000', '9000', '12000', '4500',
       '5000', '3000'], dtype='<U11')

In [92]:
print("\nQ13.2: Check if any customer ID contains '100'")
np.char.find(banking_data[:,0].astype(str),'100')>=0


Q13.2: Check if any customer ID contains '100'


array([ True,  True, False,  True,  True,  True,  True,  True,  True,
        True])

In [91]:
print("\nQ13.3: Convert all customer IDs to uppercase (if they were strings)")
np.char.upper(banking_data[:,0].astype(str))


Q13.3: Convert all customer IDs to uppercase (if they were strings)


array(['1009', '1008', '1010', '1005', '1004', '1007', '1002', '1006',
       '1001', '1003'], dtype='<U11')

In [93]:
print("\nQ13.4: Count the length of each customer ID string")
np.char.str_len(banking_data[:,0].astype(str))


Q13.4: Count the length of each customer ID string


array([4, 4, 4, 4, 4, 4, 4, 4, 4, 4])

In [95]:
print("\nQ13.5: Replace '100' with 'CUST' in customer IDs")
np.char.replace(banking_data[:,0].astype(str),'100','CUST')


Q13.5: Replace '100' with 'CUST' in customer IDs


array(['CUST9', 'CUST8', '1010', 'CUST5', 'CUST4', 'CUST7', 'CUST2',
       'CUST6', 'CUST1', 'CUST3'], dtype='<U5')

Question 14: Date and Time Operations

In [97]:
print("\nQ14.1: Convert years active to months")
banking_data[:,4]*24 


Q14.1: Convert years active to months


array([216,  24,  96, 144, 240, 168, 192,  72, 120,  48])

In [99]:
print("\nQ14.2: Calculate the average years active")
np.mean(banking_data[:,4])


Q14.2: Calculate the average years active


5.5

In [100]:
print("\nQ14.3: Find customers who have been active for more than 5 years")
banking_data[banking_data[:,4]>5]


Q14.3: Find customers who have been active for more than 5 years


array([[ 1009, 11000,   750,    35,     9],
       [ 1005,  7000,   710,    20,     6],
       [ 1004, 15000,   800,    40,    10],
       [ 1007,  9000,   730,    30,     7],
       [ 1002, 12000,   680,    25,     8]])

In [102]:
print("\nQ14.4: Calculate the total time all customers have been active (in years)")
np.sum(banking_data[:,4])


Q14.4: Calculate the total time all customers have been active (in years)


55

In [104]:
print("\nQ14.5: Find the customer with the shortest time active")
banking_data[np.argmin(banking_data[:,4])]


Q14.5: Find the customer with the shortest time active


array([1008, 2000,  600,    8,    1])

Question 15: Advanced Array Operations

In [105]:
print("\nQ15.1: Apply a function to calculate 5% interest on all account balances")
def calculate_intrest(x):
    return x*0.5
np.vectorize(calculate_intrest)(banking_data[:,1])


Q15.1: Apply a function to calculate 5% interest on all account balances


array([5500., 1000., 3000., 3500., 7500., 4500., 6000., 2250., 2500.,
       1500.])

In [108]:
print("\nQ15.2: Use np.where to categorize customers by balance ranges")
categories=np.where(banking_data[:,1]<10000,"Low Balance",
                    np.where((banking_data[:,1]>=10000)&(banking_data[:,1]<50000),"Medium Balance",
                    "High Balance"))
print(categories)



Q15.2: Use np.where to categorize customers by balance ranges
['Medium Balance' 'Low Balance' 'Low Balance' 'Low Balance'
 'Medium Balance' 'Low Balance' 'Medium Balance' 'Low Balance'
 'Low Balance' 'Low Balance']


In [109]:
print("\nQ15.3: Use np.select to categorize customers by credit score ranges")
conditions=[
    banking_data[:,2]<600,
    (banking_data[:,2]>=600)&(banking_data[:,2]<=750),
    banking_data[:,2]>750
]
choices=["poor credit","Average credit","Excellent credit"]
categories=np.select(conditions,choices)
print(categories)


Q15.3: Use np.select to categorize customers by credit score ranges
['Average credit' 'Average credit' 'Average credit' 'Average credit'
 'Excellent credit' 'Average credit' 'Average credit' 'Average credit'
 'Average credit' 'Average credit']


In [111]:
print("\nQ15.4: Use np.piecewise to apply different interest rates based on balance")
def low_intrest(x):
    return x*0.03
def mid_intrest(x):
    return x*0.05
def high_intrest(x):
    return x*0.07

np.piecewise(
    banking_data[:,1],
    [banking_data[:,1]<10000,(banking_data[:,1]>10000) & (banking_data[:,1]<50000), banking_data[:,1]>=50000],
    [low_intrest,mid_intrest,high_intrest]
)


Q15.4: Use np.piecewise to apply different interest rates based on balance


array([550,  60, 180, 210, 750, 270, 600, 135, 150,  90])

In [116]:
print("\nQ15.5: Use np.apply_along_axis to calculate the sum of each row")
np.apply_along_axis(np.sum,1,banking_data)


Q15.5: Use np.apply_along_axis to calculate the sum of each row


array([12803,  3617,  7722,  8741, 16854, 10774, 13715,  6161,  6741,
        4665])

Question 16: Array Concatenation and Stacking

In [120]:
print("\nQ16.1: Concatenate two arrays horizontally using np.hstack()")
arr1=np.array([1,2,3])
arr2=np.array([6,7,8])
np.hstack([arr1,arr2])


Q16.1: Concatenate two arrays horizontally using np.hstack()


array([1, 2, 3, 6, 7, 8])

In [121]:
print("\nQ16.2: Concatenate two arrays vertically using np.vstack()")
np.vstack([arr1,arr2])


Q16.2: Concatenate two arrays vertically using np.vstack()


array([[1, 2, 3],
       [6, 7, 8]])

In [122]:
print("\nQ16.3: Concatenate arrays along a specific axis using np.concatenate()")
np.concatenate([arr1,arr2])


Q16.3: Concatenate arrays along a specific axis using np.concatenate()


array([1, 2, 3, 6, 7, 8])

In [124]:
print("\nQ16.4: Stack arrays depth-wise using np.dstack()")
np.dstack([arr1,arr2])


Q16.4: Stack arrays depth-wise using np.dstack()


array([[[1, 6],
        [2, 7],
        [3, 8]]])

In [125]:
print("\nQ16.5: Create a column stack using np.column_stack()")
np.column_stack([arr1,arr2])


Q16.5: Create a column stack using np.column_stack()


array([[1, 6],
       [2, 7],
       [3, 8]])

Question 17: Array Splitting Operations

In [127]:
print("\nQ17.1: Split an array into 3 equal parts using np.split()")
arr_to_split = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
split_parts = np.split(arr_to_split, 3)
split_parts
for i, part in enumerate(split_parts):
    print(f" part {i+1} : {part}")


Q17.1: Split an array into 3 equal parts using np.split()
 part 1 : [1 2 3]
 part 2 : [4 5 6]
 part 3 : [7 8 9]


In [130]:
print("\nQ17.2: Split an array at specific indices using np.split()")
split_array=np.split(arr_to_split,[4,5])
split_array
for i, part in enumerate(split_array):
    print(f" part {i+1}: {part}")



Q17.2: Split an array at specific indices using np.split()
 part 1: [1 2 3 4]
 part 2: [5]
 part 3: [6 7 8 9]


In [132]:
print("\nQ17.3: Split an array horizontally using np.hsplit()")
split_horiz=np.hsplit(arr_to_split,3)
split_horiz


Q17.3: Split an array horizontally using np.hsplit()


[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

In [133]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
hsplit_parts = np.hsplit(arr_2d, 3)
hsplit_parts
for i, part in enumerate(hsplit_parts):
    print(f"Horizontal part{i+1}:\n{part}")

Horizontal part1:
[[1]
 [4]]
Horizontal part2:
[[2]
 [5]]
Horizontal part3:
[[3]
 [6]]


In [136]:
print("\nQ17.4: Split an array vertically using np.vsplit()")
vsplit_parts=np.vsplit(arr_2d,2)
for i,part in enumerate(vsplit_parts):
    print(f"part{i+1}:\n{part}")


Q17.4: Split an array vertically using np.vsplit()
part1:
[[1 2 3]]
part2:
[[4 5 6]]


In [137]:
print("\nQ17.5: Split an array into equal chunks using np.array_split()")
array_split=np.array_split(arr_2d,2)
array_split
for i, parts in enumerate(array_split):
    print(f"parts{i+1}:\n{parts}")


Q17.5: Split an array into equal chunks using np.array_split()
parts1:
[[1 2 3]]
parts2:
[[4 5 6]]


Question 18: Array Repetition and Tiling

In [142]:
print("\Q18.1: Repeat each element of an array 3 times using np.repeat()")
np.repeat(arr1,3)

\Q18.1: Repeat each element of an array 3 times using np.repeat()


<>:1: SyntaxWarning: invalid escape sequence '\Q'
<>:1: SyntaxWarning: invalid escape sequence '\Q'
C:\Users\USER\AppData\Local\Temp\ipykernel_11436\1708453127.py:1: SyntaxWarning: invalid escape sequence '\Q'
  print("\Q18.1: Repeat each element of an array 3 times using np.repeat()")


array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [141]:
print("\nQ18.2: Repeat an entire array 2 times using np.tile()")
np.tile(arr2,2)


Q18.2: Repeat an entire array 2 times using np.tile()


array([6, 7, 8, 6, 7, 8])

In [148]:
print("\nQ18.3: Repeat a 2D array using np.tile()")
np.tile(arr_2d,(3,3))


Q18.3: Repeat a 2D array using np.tile()


array([[1, 2, 3, 1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6, 4, 5, 6],
       [1, 2, 3, 1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6, 4, 5, 6],
       [1, 2, 3, 1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6, 4, 5, 6]])

In [150]:
print("\nQ18.4: Create a pattern using np.tile()")
pattern = np.tile([1, 2, 3], (4, 2))
print(pattern)


Q18.4: Create a pattern using np.tile()
[[1 2 3 1 2 3]
 [1 2 3 1 2 3]
 [1 2 3 1 2 3]
 [1 2 3 1 2 3]]


In [152]:
print("\nQ18.5: Repeat elements with different counts using np.repeat()")
np.repeat([1,2,3],[4,5,6])


Q18.5: Repeat elements with different counts using np.repeat()


array([1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3])

Q18.5: Repeat elements with different counts using np.repeat()

In [154]:
print("\nQ19.1: Compare two arrays for equality using np.array_equal()")
arr1= np.array([1, 2, 3])
arr2= np.array([1, 2, 3])
arr3 = np.array([1, 2, 4])
print(f"A equals B: {np.array_equal(arr1, arr2)}")
print(f"A equals C: {np.array_equal(arr2, arr3)}")


Q19.1: Compare two arrays for equality using np.array_equal()
A equals B: True
A equals C: False


In [167]:
print("\nQ19.2: Check if arrays are close using np.allclose()")
arr_d = np.array([1.0, 2.0, 3.0])
arr_e = np.array([1.001, 2.001, 3.001])
print(f"Arrays are close: {np.allclose(arr_d, arr_e, atol=0.01)}")


Q19.2: Check if arrays are close using np.allclose()
Arrays are close: True


In [166]:
print("\nQ19.3: Apply logical AND operation between arrays")
logical_and = np.logical_and(arr1 >= 1, arr1 < 3)
print(f"Array: {arr1}")
print(f"Logical AND (1 < x < 3): {logical_and}")


Q19.3: Apply logical AND operation between arrays
Array: [1 2 3]
Logical AND (1 < x < 3): [ True  True False]


In [165]:
print("\nQ19.4: Apply logical OR operation between arrays")
logical_or = np.logical_or(arr1 == 1, arr1 == 3)
print(f"Array: {arr1}")
print(f"Logical OR (x == 1 OR x == 3): {logical_or}")


Q19.4: Apply logical OR operation between arrays
Array: [1 2 3]
Logical OR (x == 1 OR x == 3): [ True False  True]


In [164]:
print("\nQ19.5: Apply logical NOT operation to an array")
logical_not = np.logical_not(arr1 == 2)
print(f"Array: {arr1}")
print(f"Logical NOT (x != 2): {logical_not}")


Q19.5: Apply logical NOT operation to an array
Array: [1 2 3]
Logical NOT (x != 2): [ True False  True]


Question 20: Array Set Operations

In [168]:
print("\nQ20.1: Find unique elements in an array using np.unique()")
arr_with_duplicates = np.array([1, 2, 2, 3, 3, 3, 4])
unique_elements = np.unique(arr_with_duplicates)
unique_elements


Q20.1: Find unique elements in an array using np.unique()


array([1, 2, 3, 4])

In [169]:
print("\nQ20.2: Find the intersection of two arrays using np.intersect1d()")
arr1= np.array([1, 2, 3, 4])
arr2= np.array([3, 4, 5, 6])
array_intersection=np.intersect1d(arr1,arr2)
print(f" array intersection:{array_intersection}")


Q20.2: Find the intersection of two arrays using np.intersect1d()
 array intersection:[3 4]


In [170]:
print("\nQ20.3: Find the union of two arrays using np.union1d()")
np.union1d(arr1,arr2)


Q20.3: Find the union of two arrays using np.union1d()


array([1, 2, 3, 4, 5, 6])

In [171]:
print("\nQ20.4: Find elements in first array but not in second using np.setdiff1d()")
np.setdiff1d(arr1,arr2)


Q20.4: Find elements in first array but not in second using np.setdiff1d()


array([1, 2])

In [172]:
print("\nQ20.5: Find the symmetric difference between two arrays using np.setxor1d()")
np.setxor1d(arr1,arr2)


Q20.5: Find the symmetric difference between two arrays using np.setxor1d()


array([1, 2, 5, 6])