In [2]:
import numpy as np
import pandas as pd

In [3]:
print("="*60)
print("NUMPY ASSIGNMENT: RETAIL DATA ANALYSIS")
print("=" * 60)

NUMPY ASSIGNMENT: RETAIL DATA ANALYSIS


In [3]:
# Create retail data: 10 rows × 5 columns
# Columns: Product_ID, Price, Quantity_Sold, Customer_Rating, Days_in_Stock
retail_data = np.array([
    [1001, 29.99, 45, 4.2, 15],
    [1002, 49.99, 32, 4.5, 8],
    [1003, 19.99, 78, 3.8, 22],
    [1004, 89.99, 12, 4.7, 5],
    [1005, 15.99, 95, 4.0, 18],
    [1006, 69.99, 28, 4.3, 12],
    [1007, 39.99, 56, 3.9, 20],
    [1008, 79.99, 18, 4.6, 7],
    [1009, 25.99, 67, 4.1, 16],
    [1010, 59.99, 34, 4.4, 10]
])

In [ ]:
print("\nORGINAL RETAIL DATA")
print(retail_data)
print(f"\nData shape:{retail_data.shape}")
print(f"\nData type:{retail_data.dtype}")


ORGINAL RETAIL DATA
[[1001.     29.99   45.      4.2    15.  ]
 [1002.     49.99   32.      4.5     8.  ]
 [1003.     19.99   78.      3.8    22.  ]
 [1004.     89.99   12.      4.7     5.  ]
 [1005.     15.99   95.      4.     18.  ]
 [1006.     69.99   28.      4.3    12.  ]
 [1007.     39.99   56.      3.9    20.  ]
 [1008.     79.99   18.      4.6     7.  ]
 [1009.     25.99   67.      4.1    16.  ]
 [1010.     59.99   34.      4.4    10.  ]]

Data shape:(10, 5)

Data type:float64


In [7]:
print("\n" + "=" * 60)
print("QUESTION 1: ARRAY CREATION AND MANIPULATION")
print("=" * 60)


QUESTION 1: ARRAY CREATION AND MANIPULATION


In [9]:
print("\nQ1.1: Create a 3x3 identity matrix using np.eye()")
identity_matrix=np.eye(4)
identity_matrix


Q1.1: Create a 3x3 identity matrix using np.eye()


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [12]:
print("\nQ1.2: Create an array of 10 zeros using np.zeros()")
zero_array=np.zeros(10)
zero_array


Q1.2: Create an array of 10 zeros using np.zeros()


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
print("\nQ1.3: Create an array of 5 ones using np.ones()")
ones_array=np.ones(10)
ones_array


Q1.3: Create an array of 5 ones using np.ones()


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [16]:
print("\nQ1.4: Create an array with values from 0 to 9 using np.arange()")
range_array=np.arange(10)
range_array


Q1.4: Create an array with values from 0 to 9 using np.arange()


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
print("\nQ1.5: Create an array with 6 evenly spaced values from 0 to 10 using np.linspace()")
np.linspace(0,10,6)


Q1.5: Create an array with 6 evenly spaced values from 0 to 10 using np.linspace()


array([ 0.,  2.,  4.,  6.,  8., 10.])

In [19]:
print("\n" + "=" * 60)
print("QUESTION 2: ARRAY ATTRIBUTES AND INFORMATION")
print("=" * 60)


QUESTION 2: ARRAY ATTRIBUTES AND INFORMATION


In [21]:
print("\nQ2.1: What is the shape of the retail_data array?")
retail_data.shape


Q2.1: What is the shape of the retail_data array?


(10, 5)

In [22]:
print("\nQ2.2: What is the data type of the retail_data array?")
retail_data.dtype


Q2.2: What is the data type of the retail_data array?


dtype('float64')

In [23]:
print("\nQ2.3: What is the size (total number of elements) of the retail_data array?")
retail_data.size


Q2.3: What is the size (total number of elements) of the retail_data array?


50

In [24]:
print("\nQ2.4: What is the number of dimensions of the retail_data array?")
retail_data.ndim


Q2.4: What is the number of dimensions of the retail_data array?


2

In [25]:
print("\nQ2.5: What is the memory size of the retail_data array in bytes?")
retail_data.nbytes


Q2.5: What is the memory size of the retail_data array in bytes?


400

In [26]:
print("\n" + "=" * 60)
print("QUESTION 3: INDEXING AND SLICING")
print("=" * 60)


QUESTION 3: INDEXING AND SLICING


In [27]:
print("\nQ3.1: Extract the first row of retail_data")
retail_data[0]


Q3.1: Extract the first row of retail_data


array([1001.  ,   29.99,   45.  ,    4.2 ,   15.  ])

In [28]:
print("\nQ3.2: Extract the last row of retail_data")
retail_data[-1]


Q3.2: Extract the last row of retail_data


array([1010.  ,   59.99,   34.  ,    4.4 ,   10.  ])

In [29]:
print("\nQ3.3: Extract the Price column (column index 1)")
retail_data[:,1]


Q3.3: Extract the Price column (column index 1)


array([29.99, 49.99, 19.99, 89.99, 15.99, 69.99, 39.99, 79.99, 25.99,
       59.99])

In [30]:
print("\nQ3.4: Extract the first 3 rows and first 2 columns")
retail_data[:3,:2]


Q3.4: Extract the first 3 rows and first 2 columns


array([[1001.  ,   29.99],
       [1002.  ,   49.99],
       [1003.  ,   19.99]])

In [31]:
print("\nQ3.5: Extract rows 2 to 5 (inclusive)")
retail_data[2:6]


Q3.5: Extract rows 2 to 5 (inclusive)


array([[1003.  ,   19.99,   78.  ,    3.8 ,   22.  ],
       [1004.  ,   89.99,   12.  ,    4.7 ,    5.  ],
       [1005.  ,   15.99,   95.  ,    4.  ,   18.  ],
       [1006.  ,   69.99,   28.  ,    4.3 ,   12.  ]])

In [32]:
print("\n" + "=" * 60)
print("QUESTION 4: MATHEMATICAL OPERATIONS")
print("=" * 60)


QUESTION 4: MATHEMATICAL OPERATIONS


In [36]:
print("\nQ4.1: Calculate the sum of all prices")
total_price = np.sum(retail_data[:, 1])
print(f"Total price: ${total_price:.2f}")



Q4.1: Calculate the sum of all prices
Total price: $481.90


In [39]:
print("\nQ4.2: Calculate the mean price")
mean_price=np.mean(retail_data[:,1])
mean_price


Q4.2: Calculate the mean price


48.19

In [44]:
print("\nQ4.3: Calculate the standard deviation of prices")
std_price=np.std(retail_data[:,1])
print(f"standard deviation of prices:{std_price:.2f}")




Q4.3: Calculate the standard deviation of prices
standard deviation of prices:24.70


In [45]:
print("\nQ4.4: Calculate the variance of prices")
var_prices=np.var(retail_data[:,1])
print(f"variance of prices:{var_prices:.2f}")


Q4.4: Calculate the variance of prices
variance of prices:609.96


In [46]:
print("\nQ4.5: Calculate the median price")
np.median(retail_data[:,1])


Q4.5: Calculate the median price


44.99

In [47]:
print("\n" + "=" * 60)
print("QUESTION 5: STATISTICAL FUNCTIONS")
print("=" * 60)


QUESTION 5: STATISTICAL FUNCTIONS


In [49]:
print("\nQ5.1: Find the minimum and maximum prices")
max_price=np.max(retail_data[:,1])
print(f"maximum price:{max_price:.2f}")
min_price=np.min(retail_data[:,1])
print(f"minimum price:{min_price:.2f}")



Q5.1: Find the minimum and maximum prices
maximum price:89.99
minimum price:15.99


In [50]:
print("\nQ5.2: Find the minimum and maximum quantities sold")
max_qun=np.max(retail_data[:,2])
print(f"maximum quantities:{max_qun:.2f}")
min_qun=np.min(retail_data[:,2])
print(f"minimum quantities:{min_qun:.2f}")



Q5.2: Find the minimum and maximum quantities sold
maximum quantities:95.00
minimum quantities:12.00


In [51]:
print("\nQ5.3: Calculate the percentile values for prices (25th, 50th, 75th)")
percentile_values=np.percentile(retail_data[:,1],[25,50,75])
percentile_values



Q5.3: Calculate the percentile values for prices (25th, 50th, 75th)


array([26.99, 44.99, 67.49])

In [59]:
print("\nQ5.4: Calculate the correlation between prices and quantities sold")
correlation=np.corrcoef(retail_data[:,1],retail_data[:,2])[0,1]
print(f"correlation:{correlation:.2f}")


Q5.4: Calculate the correlation between prices and quantities sold
correlation:-0.93


In [62]:
print("\nQ5.5: Calculate the covariance between prices and quantities sold")
covariance=np.cov(retail_data[:,1],retail_data[:,2])[0,1]
print(f"covariance:{covariance:.2f}")


Q5.5: Calculate the covariance between prices and quantities sold
covariance:-653.44


In [63]:
print("\n" + "=" * 60)
print("QUESTION 6: ARRAY RESHAPING AND MANIPULATION")
print("=" * 60)


QUESTION 6: ARRAY RESHAPING AND MANIPULATION


In [68]:
print("\nQ6.1: Reshape the retail_data to 5 rows × 10 columns")
#retail_data.reshape(5,10)
reshaped_5x10 = retail_data.reshape(5,10)
print(reshaped_5x10)



Q6.1: Reshape the retail_data to 5 rows × 10 columns
[[1001.     29.99   45.      4.2    15.   1002.     49.99   32.      4.5
     8.  ]
 [1003.     19.99   78.      3.8    22.   1004.     89.99   12.      4.7
     5.  ]
 [1005.     15.99   95.      4.     18.   1006.     69.99   28.      4.3
    12.  ]
 [1007.     39.99   56.      3.9    20.   1008.     79.99   18.      4.6
     7.  ]
 [1009.     25.99   67.      4.1    16.   1010.     59.99   34.      4.4
    10.  ]]


In [69]:
print("\nQ6.2: Flatten the retail_data to a 1D array")
retail_data.flatten()


Q6.2: Flatten the retail_data to a 1D array


array([1001.  ,   29.99,   45.  ,    4.2 ,   15.  , 1002.  ,   49.99,
         32.  ,    4.5 ,    8.  , 1003.  ,   19.99,   78.  ,    3.8 ,
         22.  , 1004.  ,   89.99,   12.  ,    4.7 ,    5.  , 1005.  ,
         15.99,   95.  ,    4.  ,   18.  , 1006.  ,   69.99,   28.  ,
          4.3 ,   12.  , 1007.  ,   39.99,   56.  ,    3.9 ,   20.  ,
       1008.  ,   79.99,   18.  ,    4.6 ,    7.  , 1009.  ,   25.99,
         67.  ,    4.1 ,   16.  , 1010.  ,   59.99,   34.  ,    4.4 ,
         10.  ])

In [70]:
print("\nQ6.3: Transpose the retail_data")
retail_data.T



Q6.3: Transpose the retail_data


array([[1001.  , 1002.  , 1003.  , 1004.  , 1005.  , 1006.  , 1007.  ,
        1008.  , 1009.  , 1010.  ],
       [  29.99,   49.99,   19.99,   89.99,   15.99,   69.99,   39.99,
          79.99,   25.99,   59.99],
       [  45.  ,   32.  ,   78.  ,   12.  ,   95.  ,   28.  ,   56.  ,
          18.  ,   67.  ,   34.  ],
       [   4.2 ,    4.5 ,    3.8 ,    4.7 ,    4.  ,    4.3 ,    3.9 ,
           4.6 ,    4.1 ,    4.4 ],
       [  15.  ,    8.  ,   22.  ,    5.  ,   18.  ,   12.  ,   20.  ,
           7.  ,   16.  ,   10.  ]])

In [77]:
print("\nQ6.4: Split the retail_data into 2 equal parts vertically")
#np.vsplit(retail_data,2)
split_vertical = np.vsplit(retail_data,2)
print("First part:")
print(split_vertical[0])
print("\nSecond part:")
print(split_vertical[1])



Q6.4: Split the retail_data into 2 equal parts vertically
First part:
[[1001.     29.99   45.      4.2    15.  ]
 [1002.     49.99   32.      4.5     8.  ]
 [1003.     19.99   78.      3.8    22.  ]
 [1004.     89.99   12.      4.7     5.  ]
 [1005.     15.99   95.      4.     18.  ]]

Second part:
[[1006.     69.99   28.      4.3    12.  ]
 [1007.     39.99   56.      3.9    20.  ]
 [1008.     79.99   18.      4.6     7.  ]
 [1009.     25.99   67.      4.1    16.  ]
 [1010.     59.99   34.      4.4    10.  ]]


In [ ]:
print("\nQ6.5: Split the retail_data into 2 equal parts horizontally")
split_horizontal=np.hsplit(retail_data,2)
print("First part")
print(split_horizontal[0])
print("second part")
print(split_horizontal[1])

In [78]:
print("\n" + "=" * 60)
print("QUESTION 7: LOGICAL OPERATIONS AND FILTERING")
print("=" * 60)



QUESTION 7: LOGICAL OPERATIONS AND FILTERING


In [5]:
print("\nQ7.1: Find products with price greater than $50")
retail_data[retail_data[:,1]>50]


Q7.1: Find products with price greater than $50


array([[1004.  ,   89.99,   12.  ,    4.7 ,    5.  ],
       [1006.  ,   69.99,   28.  ,    4.3 ,   12.  ],
       [1008.  ,   79.99,   18.  ,    4.6 ,    7.  ],
       [1010.  ,   59.99,   34.  ,    4.4 ,   10.  ]])

In [6]:
print("\nQ7.2: Find products with customer rating greater than 4.0")
retail_data[retail_data[:,3]>4.0]


Q7.2: Find products with customer rating greater than 4.0


array([[1001.  ,   29.99,   45.  ,    4.2 ,   15.  ],
       [1002.  ,   49.99,   32.  ,    4.5 ,    8.  ],
       [1004.  ,   89.99,   12.  ,    4.7 ,    5.  ],
       [1006.  ,   69.99,   28.  ,    4.3 ,   12.  ],
       [1008.  ,   79.99,   18.  ,    4.6 ,    7.  ],
       [1009.  ,   25.99,   67.  ,    4.1 ,   16.  ],
       [1010.  ,   59.99,   34.  ,    4.4 ,   10.  ]])

In [8]:
print("\nQ7.3: Find products with quantity sold greater than 50 AND price less than $40")
retail_data[(retail_data[:,2]>50)&(retail_data[:,1]<40)]


Q7.3: Find products with quantity sold greater than 50 AND price less than $40


array([[1003.  ,   19.99,   78.  ,    3.8 ,   22.  ],
       [1005.  ,   15.99,   95.  ,    4.  ,   18.  ],
       [1007.  ,   39.99,   56.  ,    3.9 ,   20.  ],
       [1009.  ,   25.99,   67.  ,    4.1 ,   16.  ]])

In [ ]:
print("\nQ7.4: Count how many products have price between $20 and $60")
price_range_count = np.sum((retail_data[:, 1] >= 20) & (retail_data[:, 1] <= 60))
print(f"Products in $20-$60 range: {price_range_count}")


Q7.4: Count how many products have price between $20 and $60


array([[1001.  ,   29.99,   45.  ,    4.2 ,   15.  ],
       [1002.  ,   49.99,   32.  ,    4.5 ,    8.  ],
       [1007.  ,   39.99,   56.  ,    3.9 ,   20.  ],
       [1009.  ,   25.99,   67.  ,    4.1 ,   16.  ],
       [1010.  ,   59.99,   34.  ,    4.4 ,   10.  ]])

In [11]:
print("\nQ7.5: Find the index of the product with the highest rating")
highest_rating_idx=np.argmax(retail_data[:,3])
print(f"Index: {highest_rating_idx}, Product ID: {retail_data[highest_rating_idx, 0]}")



Q7.5: Find the index of the product with the highest rating
Index: 3, Product ID: 1004.0


In [12]:
print("\n" + "=" * 60)
print("QUESTION 8: SORTING AND SEARCHING")
print("=" * 60)



QUESTION 8: SORTING AND SEARCHING


In [13]:
print("\nQ8.1: Sort the retail_data by price (ascending)")
sorted_by_price = retail_data[retail_data[:, 1].argsort()]
print(sorted_by_price)


Q8.1: Sort the retail_data by price (ascending)
[[1005.     15.99   95.      4.     18.  ]
 [1003.     19.99   78.      3.8    22.  ]
 [1009.     25.99   67.      4.1    16.  ]
 [1001.     29.99   45.      4.2    15.  ]
 [1007.     39.99   56.      3.9    20.  ]
 [1002.     49.99   32.      4.5     8.  ]
 [1010.     59.99   34.      4.4    10.  ]
 [1006.     69.99   28.      4.3    12.  ]
 [1008.     79.99   18.      4.6     7.  ]
 [1004.     89.99   12.      4.7     5.  ]]


In [14]:
print("\nQ8.2: Sort the retail_data by quantity sold (descending)")
sorted_by_desc=retail_data[(-retail_data[:,2]).argsort()]
sorted_by_desc



Q8.2: Sort the retail_data by quantity sold (descending)


array([[1005.  ,   15.99,   95.  ,    4.  ,   18.  ],
       [1003.  ,   19.99,   78.  ,    3.8 ,   22.  ],
       [1009.  ,   25.99,   67.  ,    4.1 ,   16.  ],
       [1007.  ,   39.99,   56.  ,    3.9 ,   20.  ],
       [1001.  ,   29.99,   45.  ,    4.2 ,   15.  ],
       [1010.  ,   59.99,   34.  ,    4.4 ,   10.  ],
       [1002.  ,   49.99,   32.  ,    4.5 ,    8.  ],
       [1006.  ,   69.99,   28.  ,    4.3 ,   12.  ],
       [1008.  ,   79.99,   18.  ,    4.6 ,    7.  ],
       [1004.  ,   89.99,   12.  ,    4.7 ,    5.  ]])

In [15]:
print("\nQ8.3: Find the indices that would sort the array by customer rating")
np.argsort(retail_data[:,3])


Q8.3: Find the indices that would sort the array by customer rating


array([2, 6, 4, 8, 0, 5, 9, 1, 7, 3], dtype=int64)

In [16]:
print("\nQ8.4: Find the product with the second highest price")
second_highest_price_idx = np.argsort(retail_data[:, 1])[-2]
second_highest_product = retail_data[second_highest_price_idx]
print(f"Product ID: {second_highest_product[0]}, Price: ${second_highest_product[1]:.2f}")


Q8.4: Find the product with the second highest price
Product ID: 1008.0, Price: $79.99


In [19]:
print("\nQ8.5: Find the product with the lowest quantity sold")
lowest_qty_idx = np.argmin(retail_data[:, 2])
lowest_qty_product = retail_data[lowest_qty_idx]
print(f"Product ID: {lowest_qty_product[0]}, Quantity: {lowest_qty_product[2]}")



Q8.5: Find the product with the lowest quantity sold
Product ID: 1004.0, Quantity: 12.0


In [18]:
print("\n" + "=" * 60)
print("QUESTION 9: MATHEMATICAL FUNCTIONS")
print("=" * 60)


QUESTION 9: MATHEMATICAL FUNCTIONS


In [20]:
print("\nQ9.1: Calculate the absolute values of all elements")
np.abs(retail_data)


Q9.1: Calculate the absolute values of all elements


array([[1001.  ,   29.99,   45.  ,    4.2 ,   15.  ],
       [1002.  ,   49.99,   32.  ,    4.5 ,    8.  ],
       [1003.  ,   19.99,   78.  ,    3.8 ,   22.  ],
       [1004.  ,   89.99,   12.  ,    4.7 ,    5.  ],
       [1005.  ,   15.99,   95.  ,    4.  ,   18.  ],
       [1006.  ,   69.99,   28.  ,    4.3 ,   12.  ],
       [1007.  ,   39.99,   56.  ,    3.9 ,   20.  ],
       [1008.  ,   79.99,   18.  ,    4.6 ,    7.  ],
       [1009.  ,   25.99,   67.  ,    4.1 ,   16.  ],
       [1010.  ,   59.99,   34.  ,    4.4 ,   10.  ]])

In [21]:
print("\nQ9.2: Calculate the square root of all prices")
np.sqrt(retail_data[:, 1])



Q9.2: Calculate the square root of all prices


array([5.47631263, 7.07036067, 4.47101778, 9.48630592, 3.9987498 ,
       8.36600263, 6.3237647 , 8.94371288, 5.09803884, 7.74532117])

In [22]:
print("\nQ9.3: Calculate the square of all quantities sold")
squared_qty = np.square(retail_data[:, 2])
squared_qty


Q9.3: Calculate the square of all quantities sold


array([2025., 1024., 6084.,  144., 9025.,  784., 3136.,  324., 4489.,
       1156.])

In [23]:
print("\nQ9.4: Calculate the exponential of all customer ratings")
np.exp(retail_data[:, 3])


Q9.4: Calculate the exponential of all customer ratings


array([ 66.68633104,  90.0171313 ,  44.70118449, 109.94717245,
        54.59815003,  73.6997937 ,  49.40244911,  99.48431564,
        60.3402876 ,  81.45086866])

In [24]:
print("\nQ9.5: Calculate the natural logarithm of all prices")
np.log(retail_data[:, 1])


Q9.5: Calculate the natural logarithm of all prices


array([3.40086399, 3.91182299, 2.99523215, 4.49969855, 2.77196353,
       4.24835237, 3.68862942, 4.38190163, 3.25771185, 4.09417788])

In [25]:
print("\n" + "=" * 60)
print("QUESTION 10: ADVANCED OPERATIONS")
print("=" * 60)


QUESTION 10: ADVANCED OPERATIONS


In [26]:
print("\nQ10.1: Calculate the cumulative sum of prices")
cumsum_prices = np.cumsum(retail_data[:, 1])
print(cumsum_prices)


Q10.1: Calculate the cumulative sum of prices
[ 29.99  79.98  99.97 189.96 205.95 275.94 315.93 395.92 421.91 481.9 ]


In [27]:
print("\nQ10.2: Calculate the cumulative product of quantities sold")
cumprod_qty = np.cumprod(retail_data[:, 2])
print(cumprod_qty)


Q10.2: Calculate the cumulative product of quantities sold
[4.50000000e+01 1.44000000e+03 1.12320000e+05 1.34784000e+06
 1.28044800e+08 3.58525440e+09 2.00774246e+11 3.61393644e+12
 2.42133741e+14 8.23254720e+15]


In [28]:
print("\nQ10.3: Calculate the difference between consecutive prices")
diff_prices = np.diff(retail_data[:, 1])
print(diff_prices)


Q10.3: Calculate the difference between consecutive prices
[ 20. -30.  70. -74.  54. -30.  40. -54.  34.]


In [29]:
print("\nQ10.4: Calculate the gradient of prices")
gradient_prices = np.gradient(retail_data[:, 1])
print(gradient_prices)


Q10.4: Calculate the gradient of prices
[ 20.  -5.  20.  -2. -10.  12.   5.  -7. -10.  34.]


In [30]:
print("\nQ10.5: Calculate the histogram of prices with 5 bins")
hist_prices, bin_edges = np.histogram(retail_data[:, 1], bins=5)
print(f"Histogram counts: {hist_prices}")
print(f"Bin edges: {bin_edges}")


Q10.5: Calculate the histogram of prices with 5 bins
Histogram counts: [4 1 2 1 2]
Bin edges: [15.99 30.79 45.59 60.39 75.19 89.99]


In [9]:
print("\n" + "=" * 60)
print("QUESTION 11: RANDOM NUMBERS AND SIMULATION")
print("=" * 60)


QUESTION 11: RANDOM NUMBERS AND SIMULATION


In [10]:
print("\nQ11.1: Generate 5 random integers between 1 and 100")
np.random.randint(1,100,5)


Q11.1: Generate 5 random integers between 1 and 100


array([61, 32, 74,  7, 84])

In [25]:
print("\nQ11.2: Generate 5 random floats between 0 and 1")
np.random.random(5)


Q11.2: Generate 5 random floats between 0 and 1


array([0.21233911, 0.18182497, 0.18340451, 0.30424224, 0.52475643])

In [18]:
print("\nQ11.3: Generate 5 random numbers from normal distribution (mean=0, std=1)")
np.random.normal(0,1,5)


Q11.3: Generate 5 random numbers from normal distribution (mean=0, std=1)


array([ 0.47659985,  0.19486021,  0.30643522, -0.18460006, -0.89290747])

In [20]:
print("\nQ11.4: Shuffle the retail_data rows randomly")
copy_data=retail_data.copy()
np.random.shuffle(copy_data)
copy_data



Q11.4: Shuffle the retail_data rows randomly


array([[1004.  ,   89.99,   12.  ,    4.7 ,    5.  ],
       [1002.  ,   49.99,   32.  ,    4.5 ,    8.  ],
       [1006.  ,   69.99,   28.  ,    4.3 ,   12.  ],
       [1001.  ,   29.99,   45.  ,    4.2 ,   15.  ],
       [1010.  ,   59.99,   34.  ,    4.4 ,   10.  ],
       [1003.  ,   19.99,   78.  ,    3.8 ,   22.  ],
       [1008.  ,   79.99,   18.  ,    4.6 ,    7.  ],
       [1009.  ,   25.99,   67.  ,    4.1 ,   16.  ],
       [1007.  ,   39.99,   56.  ,    3.9 ,   20.  ],
       [1005.  ,   15.99,   95.  ,    4.  ,   18.  ]])

In [ ]:
print("\nQ11.5: Set random seed to 42 and generate 3 random numbers")
np.random.seed(42)
seeded_random = np.random.random(3)
print(seeded_random)


Q11.5: Set random seed to 42 and generate 3 random numbers
[0.37454012 0.95071431 0.73199394]


In [26]:
print("\n" + "=" * 60)
print("QUESTION 12: LINEAR ALGEBRA OPERATIONS")
print("=" * 60)


QUESTION 12: LINEAR ALGEBRA OPERATIONS


In [29]:
print("\nQ12.1: Calculate the dot product of price and quantity columns")
np.dot(retail_data[:,1],retail_data[:,2])


Q12.1: Calculate the dot product of price and quantity columns


16527.35

In [31]:
print("\nQ12.2: Calculate the cross product of first two rows")
np.cross(retail_data[0,:3],retail_data[1,:3])


Q12.2: Calculate the cross product of first two rows


array([-1289.87, 13058.  , 19990.01])

In [32]:
print("\nQ12.3: Calculate the norm (magnitude) of the price column")
np.linalg.norm(retail_data[:,1])


Q12.3: Calculate the norm (magnitude) of the price column


171.23773240731728

In [35]:
print("\nQ12.4: Create a 2x2 matrix and calculate its determinant")
matrix_2x2 = np.array([[2, 3], [1, 4]])
determinant = np.linalg.det(matrix_2x2)
print(f"Matrix:\n{matrix_2x2}")
print(f"Determinant: {determinant}")



Q12.4: Create a 2x2 matrix and calculate its determinant
Matrix:
[[2 3]
 [1 4]]
Determinant: 5.000000000000001


In [36]:
print("\nQ12.5: Calculate the inverse of the 2x2 matrix")
np.linalg.inv(matrix_2x2)


Q12.5: Calculate the inverse of the 2x2 matrix


array([[ 0.8, -0.6],
       [-0.2,  0.4]])

In [37]:
print("\n" + "=" * 60)
print("QUESTION 13: STRING OPERATIONS")
print("=" * 60)


QUESTION 13: STRING OPERATIONS


In [38]:
print("\nQ13.1: Convert all product IDs to strings")
retail_data[:,0].astype(str)


Q13.1: Convert all product IDs to strings


array(['1001.0', '1002.0', '1003.0', '1004.0', '1005.0', '1006.0',
       '1007.0', '1008.0', '1009.0', '1010.0'], dtype='<U32')

In [39]:
print("\nQ13.2: Check if any product ID contains '100'")
np.char.find(retail_data[:,0].astype(str),'100')>=0


Q13.2: Check if any product ID contains '100'


array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False])

In [40]:
print("\nQ13.3: Convert all product IDs to uppercase (if they were strings)")
np.char.upper(retail_data[:,0].astype(str))


Q13.3: Convert all product IDs to uppercase (if they were strings)


array(['1001.0', '1002.0', '1003.0', '1004.0', '1005.0', '1006.0',
       '1007.0', '1008.0', '1009.0', '1010.0'], dtype='<U32')

In [41]:
print("\nQ13.4: Count the length of each product ID string")
np.char.str_len(retail_data[:,0].astype(str))


Q13.4: Count the length of each product ID string


array([6, 6, 6, 6, 6, 6, 6, 6, 6, 6])

In [42]:
print("\nQ13.5: Replace '100' with 'PROD' in product IDs")
np.char.replace(retail_data[:,0].astype(str),'100','PROD')


Q13.5: Replace '100' with 'PROD' in product IDs


array(['PROD1.0', 'PROD2.0', 'PROD3.0', 'PROD4.0', 'PROD5.0', 'PROD6.0',
       'PROD7.0', 'PROD8.0', 'PROD9.0', '1010.0'], dtype='<U7')

In [43]:
print("\n" + "=" * 60)
print("QUESTION 14: DATE AND TIME OPERATIONS")
print("=" * 60)


QUESTION 14: DATE AND TIME OPERATIONS


In [44]:
print("\nQ14.1: Convert days in stock to hours")
retail_data[:,4]*24



Q14.1: Convert days in stock to hours


array([360., 192., 528., 120., 432., 288., 480., 168., 384., 240.])

In [45]:
print("\nQ14.2: Calculate the average days in stock")
np.mean(retail_data[:,4])


Q14.2: Calculate the average days in stock


13.3

In [46]:
print("\nQ14.3: Find products that have been in stock for more than 15 days")
retail_data[retail_data[:,4]>15]


Q14.3: Find products that have been in stock for more than 15 days


array([[1003.  ,   19.99,   78.  ,    3.8 ,   22.  ],
       [1005.  ,   15.99,   95.  ,    4.  ,   18.  ],
       [1007.  ,   39.99,   56.  ,    3.9 ,   20.  ],
       [1009.  ,   25.99,   67.  ,    4.1 ,   16.  ]])

In [47]:
print("\nQ14.4: Calculate the total time all products have been in stock (in days)")
np.sum(retail_data[:,4])


Q14.4: Calculate the total time all products have been in stock (in days)


133.0

In [48]:
print("\nQ14.5: Find the product with the shortest time in stock")
retail_data[np.argmin(retail_data[:,4])]


Q14.5: Find the product with the shortest time in stock


array([1004.  ,   89.99,   12.  ,    4.7 ,    5.  ])

In [49]:
print("\n" + "=" * 60)
print("QUESTION 15: ADVANCED ARRAY OPERATIONS")
print("=" * 60)


QUESTION 15: ADVANCED ARRAY OPERATIONS


In [3]:
print("\nQ15.1: Apply a function to square all prices")
def square_price(x):
    return x**2
np.vectorize(square_price)(retail_data[:,1])


Q15.1: Apply a function to square all prices


array([ 899.4001, 2499.0001,  399.6001, 8098.2001,  255.6801, 4898.6001,
       1599.2001, 6398.4001,  675.4801, 3598.8001])

In [4]:
print("\nQ15.2: Use np.where to replace prices > $50 with 'Expensive' and others with 'Affordable'")
np.where(retail_data[:,1]>50,'Expensive','Affordable')


Q15.2: Use np.where to replace prices > $50 with 'Expensive' and others with 'Affordable'


array(['Affordable', 'Affordable', 'Affordable', 'Expensive',
       'Affordable', 'Expensive', 'Affordable', 'Expensive', 'Affordable',
       'Expensive'], dtype='<U10')

In [6]:
print("\nQ15.3: Use np.select to categorize products by price ranges")
conditions=[
    retail_data[:,1]<20,
    (retail_data[:,1]>=20)&(retail_data[:,1]<50),
    retail_data[:,1]>=50
]
choices=['Budget','Mid-range','Expensive']
np.select(conditions,choices,default='Unknown')


Q15.3: Use np.select to categorize products by price ranges


array(['Mid-range', 'Mid-range', 'Budget', 'Expensive', 'Budget',
       'Expensive', 'Mid-range', 'Expensive', 'Mid-range', 'Expensive'],
      dtype='<U9')

In [8]:
print("\nQ15.4: Use np.piecewise to apply different functions based on price ranges")
def low_price(x):
    return x*0.9
def mid_price(x):
    return x*1.0
def high_price(x):
    return x*1.1

np.piecewise(
    retail_data[:,1],
    [retail_data[:,1]<20,(retail_data[:,1]>20) & (retail_data[:,1]<50), retail_data[:,1]>=50],
    [low_price,mid_price,high_price]
)


Q15.4: Use np.piecewise to apply different functions based on price ranges


array([29.99 , 49.99 , 17.991, 98.989, 14.391, 76.989, 39.99 , 87.989,
       25.99 , 65.989])

In [9]:
print("\nQ15.5: Use np.apply_along_axis to calculate the sum of each row")
np.apply_along_axis(np.sum,1,retail_data)


Q15.5: Use np.apply_along_axis to calculate the sum of each row


array([1095.19, 1096.49, 1126.79, 1115.69, 1137.99, 1120.29, 1126.89,
       1117.59, 1122.09, 1118.39])

In [10]:
print("\n" + "=" * 60)
print("QUESTION 16: ARRAY CONCATENATION AND STACKING")
print("=" * 60)


QUESTION 16: ARRAY CONCATENATION AND STACKING


In [4]:
print("\nQ16.1: Concatenate two arrays horizontally using np.hstack()")
arr1=np.array([1,2,3])
arr2=np.array([6,7,8])
np.hstack([arr1,arr2])


Q16.1: Concatenate two arrays horizontally using np.hstack()


array([1, 2, 3, 6, 7, 8])

In [12]:
print("\nQ16.2: Concatenate two arrays vertically using np.vstack()")
np.vstack([arr1,arr2])


Q16.2: Concatenate two arrays vertically using np.vstack()


array([[1, 2, 3],
       [6, 7, 8]])

In [15]:
print("\nQ16.3: Concatenate arrays along a specific axis using np.concatenate()")
np.concatenate([arr1,arr2],axis=0)


Q16.3: Concatenate arrays along a specific axis using np.concatenate()


array([1, 2, 3, 6, 7, 8])

In [16]:
print("\nQ16.4: Stack arrays depth-wise using np.dstack()")
np.stack([arr1,arr2])


Q16.4: Stack arrays depth-wise using np.dstack()


array([[1, 2, 3],
       [6, 7, 8]])

In [17]:
print("\nQ16.5: Create a column stack using np.column_stack()")
np.column_stack([arr1,arr2])


Q16.5: Create a column stack using np.column_stack()


array([[1, 6],
       [2, 7],
       [3, 8]])

In [18]:
print("\n" + "=" * 60)
print("QUESTION 17: ARRAY SPLITTING OPERATIONS")
print("=" * 60)


QUESTION 17: ARRAY SPLITTING OPERATIONS


In [23]:
print("\nQ17.1: Split an array into 3 equal parts using np.split()")
arr_to_split = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
split_parts = np.split(arr_to_split, 3)
split_parts
for i, part in enumerate(split_parts):
    print(f"Part {i+1}: {part}")


Q17.1: Split an array into 3 equal parts using np.split()
Part 1: [1 2 3]
Part 2: [4 5 6]
Part 3: [7 8 9]


In [28]:
print("\nQ17.2: Split an array at specific indices using np.split()")
split_at_indices=np.split(arr_to_split,[4,6])
for i, part in enumerate(split_at_indices):
    print(f"Part {i+1}: {part}")


Q17.2: Split an array at specific indices using np.split()
Part 1: [1 2 3 4]
Part 2: [5 6]
Part 3: [7 8 9]


In [30]:
print("\nQ17.3: Split an array horizontally using np.hsplit()")
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
hsplit_parts = np.hsplit(arr_2d, 3)
hsplit_parts
for i, part in enumerate(hsplit_parts):
    print(f"Horizontal part{i+1}:\n{part}")


Q17.3: Split an array horizontally using np.hsplit()
Horizontal part1:
[[1]
 [4]]
Horizontal part2:
[[2]
 [5]]
Horizontal part3:
[[3]
 [6]]


In [32]:
print("\nQ17.4: Split an array vertically using np.vsplit()")
vsplit_parts=np.vsplit(arr_2d,2)
for i,part in enumerate(vsplit_parts):
    print(f"part{i+1}:\n{part}")


Q17.4: Split an array vertically using np.vsplit()
part1:
[[1 2 3]]
part2:
[[4 5 6]]


In [36]:
print("\nQ17.5: Split an array into equal chunks using np.array_split()")
array_split=np.array_split(arr_2d,2)
array_split
for i, parts in enumerate(array_split):
    print(f"parts{i+1}:\n{parts}")


Q17.5: Split an array into equal chunks using np.array_split()
parts1:
[[1 2 3]]
parts2:
[[4 5 6]]


In [37]:
print("\n" + "=" * 60)
print("QUESTION 18: ARRAY REPETITION AND TILING")
print("=" * 60)


QUESTION 18: ARRAY REPETITION AND TILING


In [5]:
print("\nQ18.1: Repeat each element of an array 3 times using np.repeat()")
np.repeat(arr1, 3)


Q18.1: Repeat each element of an array 3 times using np.repeat()


array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [6]:
print("\nQ18.2: Repeat an entire array 2 times using np.tile()")
np.tile(arr1, 2)


Q18.2: Repeat an entire array 2 times using np.tile()


array([1, 2, 3, 1, 2, 3])

In [7]:
print("\nQ18.3: Repeat a 2D array using np.tile()")
print("Answer:")
arr_2d_small = np.array([[1, 2], [3, 4]])
tiled_2d = np.tile(arr_2d_small, (2, 3))
tiled_2d


Q18.3: Repeat a 2D array using np.tile()
Answer:


array([[1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4],
       [1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4]])